---

clone:
  git-clone:
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
    image: "blang/latex:ctanfull"

kind: pipeline
name: docs

steps:
- name: html
  image: "ddidier/sphinx-doc:3.5.4-1"
  environment:
    USER_ID: $UID
  commands:
    - "pip install pydata-sphinx-theme"
    - "make html"
    - "make linkcheck"
  depends_on: [ clone ]

- name: markdown-link-check
  image: casperlabs/node-build-u1804
  commands:
    - "./ci/markdown_link_check.sh"
  depends_on: [ clone ]

trigger:
  branch:
    - master
